### ISSUE TITLE
Doesn't detect installation status

### ISSUE THREAD

**Issue by yutsi** [nbear3/Dolphin-Updater#11]
I have the latest nightly build of Dolphin installed and just installed the Dolphin Updater. It doesn't detect my current installation status.
![dolphinupdater-issue](https://user-images.githubusercontent.com/733713/35174337-014a34f2-fd3d-11e7-9887-deeccb3b4e54.PNG)

**Comment by nbear3** [comment]
You have to download through Dolphin Updater at least once before it can detect your version

**Comment by yutsi** [comment]
Thanks!
