### ISSUE TITLE
Does not update anymore

### ISSUE THREAD

**Issue by reloxx13** [nbear3/Dolphin-Updater#2]
If i start the update, it says its updated now and shows current version with newest.

Then i run Dolphin and its still an old verison.

Tried as admin, changing path, reset local version and cmd tool.

Windows 10

![unbenannt](https://user-images.githubusercontent.com/14855001/30656660-1e5838a8-9e35-11e7-8ea0-23012a3af05f.PNG)

**Comment by reloxx13** [comment]
found the problem:
> ERROR:
> Can't load module 7z.dll

my pull request is not allowed, so here is my solution:
i use 7za.exe with 7za.dll instead of 7z.exe
put the new files in res folder
change comand in scripts from 7z to 7za.exe

![unbenannt](https://user-images.githubusercontent.com/14855001/30663407-dcdf2330-9e4a-11e7-98ef-1fbff2d22bb9.PNG)

**Comment by reloxx13** [comment]
Here is a Version with 7za.exe instead of 7z.exe cuz i dont know if this GIT will be updated.

[DolphinUpdateSetup_2_5_1.zip](https://github.com/nbear3/Dolphin-Updater/files/1319076/DolphinUpdateSetup_2_5_1.zip)

PS: its not written in the readme, but the selected dolphin folder must be exactly named "Dolphin-x64"

**Comment by nbear3** [comment]
I pushed out your change, should be packaged with the correct 7-zip files now.

Also, the folder should work with any name which is why it is not in the readme.
