### ISSUE TITLE
Stop auto launch function

### ISSUE THREAD

**Issue by reloxx13** [nbear3/Dolphin-Updater#6]
Heya,

if you activate the auto launch function, there is no way to stop it ( try hard to spam checkbox position while launching :D )

i tried to add a keypress event e.g. hold key shift after double clicking but the update thread is faster.

A diffrent solution i had was to wait 3sec before auto launch if there was an update, but i could not get it to work async without blocking the app :X

Easiest solution: stop auto launch if there was an update.

**Comment by nbear3** [comment]
I think my computer is slower because I can click it, but I can see how it could be a problem. Do you mean it launches too fast if there is no update? If there's an update it will spend a lot of time downloading the new version

**Comment by reloxx13** [comment]
yup, 1-2 sec time to hit the checkbox :p

i made a small video, but the screen record tool slows down the open process, its a lil bit faster.

https://streamable.com/7puxm

ill wait for an update to check the loading time with download.

**Comment by nbear3** [comment]
I pushed to the dev branch that has a 1-second delay before launching. I also made it so you can hold shift to stop auto-launch. Let me know if that's what you were thinking

**Comment by reloxx13** [comment]
works perfect 🥇
